"""HTML to PDF, then real page numbers in the contents and a navigable outline.

Two passes, and the second one is not optional polish.

CSS has a mechanism for contents page numbers, `target-counter(attr(href), page)`, and the browser
engine used here does not implement it. Rather than ship a 50-page document whose contents makes a
reader hunt, the numbers are resolved from the RENDERED document: render once, find the page each
heading actually landed on, write those numbers into a THROWAWAY COPY of the HTML, render that
again, and attach a PDF outline so the viewer sidebar works too.

The copy is the whole point of the second pass's design. The published HTML has already been
judged by the claims gate by the time this runs, and an artifact the gate passed may not be edited
afterwards by anything: the file a reader receives has to be the file that was verified.

The second render is safe because a page number is appended to an existing single-line contents
entry, so nothing reflows. That is asserted at the end rather than assumed, because "probably still
correct" is not a standard worth publishing.

Requires playwright for rendering and pymupdf for the outline. Both are optional: the rest of the
tool has no third-party dependencies, and a caller without them gets a clear message rather than a
traceback.
"""
import io
import os
import re

FOOTER_TEMPLATE = """
<div style="width:100%%;font-size:8px;color:#666;padding:0 14mm;
            font-family:-apple-system,'Segoe UI',Roboto,sans-serif;
            display:flex;justify-content:space-between;">
  <span>%s</span>
  <span>Page <span class="pageNumber"></span> of <span class="totalPages"></span></span>
</div>
"""
EMPTY_HEADER = '<div style="display:none"></div>'

# The one thing the footer prints that the document does not: its own page numbering, generated by
# the renderer from FOOTER_TEMPLATE above. A check comparing what the PDF prints against what the
# judged HTML printed has to account for it, or it reports every page number in a fifty-page
# document as a figure that appeared from nowhere. Matched here rather than guessed at by the
# caller, because this is the module that emits it.
FOOTER_NUMBERING = re.compile(r"Page\s+\d+\s+of\s+\d+")

# A draft stamp belongs on EVERY page of a PDF, not only on the one carrying the banner: a PDF is
# read, printed and screenshotted a page at a time, and page 23 on its own must still say what it
# is. The banner in the HTML covers the first page; this covers the rest.
DRAFT_FOOTER = '<span style="color:#7f1d1d;font-weight:700">%s</span>&nbsp;&nbsp;&nbsp;'

# The greppable half of the same stamp, in the footer of every page so that extracting the text of
# any single page finds it. Small and grey because it is addressed to a script, not to a reader.
DRAFT_MARKER_FOOTER = '&nbsp;&nbsp;<span style="color:#999;font-size:6px">%s</span>'


def _require(mod, why):
    """Import an optional dependency, or explain precisely what to install and why.

    importlib rather than __import__, because __import__("playwright") returns the package without
    binding its submodules and the resulting AttributeError names nothing useful.
    """
    import importlib
    try:
        return importlib.import_module(mod)
    except ImportError:
        raise SystemExit(
            "%s is needed to %s but is not installed.\n"
            "  pip install %s\n"
            "The rest of this tool has no third-party dependencies; only PDF export does."
            % (mod, why, {"playwright.sync_api": "playwright && playwright install chromium",
                          "fitz": "pymupdf"}.get(mod, mod)))


def render(html_path, out_path=None, footer_left="", draft_note="", draft_marker=""):
    """Render an HTML file to PDF with a page footer. Returns the output path.

    `draft_note`, when set, is stamped in red at the left of every page footer.

    `draft_marker` is the pipeline-readable half of the same stamp. It goes into the footer as
    text rather than into the metadata alone, because footer text is on every page and comes back
    out of any text extraction, which is what a pre-send check actually has to hand. A banner only
    a person can read is a note, not a control.
    """
    sync_playwright = _require("playwright.sync_api", "render a PDF").sync_playwright
    src = os.path.abspath(html_path)
    out = os.path.abspath(out_path or (os.path.splitext(src)[0] + ".pdf"))
    left = (DRAFT_FOOTER % draft_note if draft_note else "") + (footer_left or "")
    if draft_marker:
        left += DRAFT_MARKER_FOOTER % draft_marker
    with sync_playwright() as pw:
        browser = pw.chromium.launch()
        page = browser.new_page()
        page.emulate_media(media="print", color_scheme="light")
        page.goto("file:///" + src.replace("\\", "/"), wait_until="load")
        # Collapsed <details> content does not print. Open them all so table views survive, which
        # is what keeps the reproducibility contract intact on paper.
        page.evaluate("document.querySelectorAll('details').forEach(d => d.open = true)")
        page.wait_for_timeout(400)
        page.pdf(path=out, format="A4", print_background=True, display_header_footer=True,
                 header_template=EMPTY_HEADER, footer_template=FOOTER_TEMPLATE % left,
                 margin={"top": "16mm", "bottom": "18mm", "left": "14mm", "right": "14mm"})
        browser.close()
    return out


CONTENTS_HEADING = "Contents"
# How much of a page's text counts as its head. A contents page announces itself at the top; a
# body page that happens to use the word does not.
CONTENTS_HEAD_CHARS = 400


def contents_end(heads):
    """The 0-based index of the last CONTENTS page, given each page's head text.

    THE BUG THIS REPLACES. The end of the contents was the LAST page anywhere in the document
    whose head mentioned the contents heading. A body page opening with that word therefore
    swallowed everything before it: every section heading up to page forty was ruled to be inside
    the contents and never mapped, which surfaces as "found no section headings" or, worse, as a
    contents page numbered from a handful of sections that happened to fall after the impostor.
    A document is not allowed to break its own pagination by discussing its own structure.

    The contents is a run of pages at the FRONT. So: find the first page that announces it, and
    extend only through pages that are immediately adjacent and announce it too (a contents long
    enough to spill onto a second page repeats its heading). A later mention is prose.

    Returns 0 when no page announces a contents at all, which leaves the title page skipped and
    every other page scanned, exactly as before.
    """
    end = 0
    seen = False
    for i, head in enumerate(heads):
        if CONTENTS_HEADING not in head:
            if seen:
                break
            continue
        if seen and i != end + 1:
            break
        seen, end = True, i
    return end


def section_pages(pdf_path):
    """Map section number -> 1-based page, from where each heading is actually drawn.

    Contents pages are skipped by contents_end above; everything after them is body. Cruder than
    parsing the layout, and far less fragile.
    """
    fitz = _require("fitz", "attach a PDF outline")
    doc = fitz.open(pdf_path)
    toc_end = contents_end([page.get_text()[:CONTENTS_HEAD_CHARS] for page in doc])
    found = {}
    for i in range(toc_end + 1, len(doc)):
        for line in doc[i].get_text().split("\n"):
            m = re.match(r"^(\d{1,2})\.\s+(\S.*)$", line.strip())
            if m and m.group(1) not in found:
                found[m.group(1)] = i + 1
    doc.close()
    return found


def _patch_contents(html, pages):
    """Write each section's real page number into its contents entry.

    Returns (html, count, inserted). `inserted` is the set of page numbers this actually wrote,
    as strings. They are the only numerals a PDF carries that its source document does not, so
    whatever checks the export against the judged HTML has to be handed them by name rather than
    left to guess a plausible range.
    """
    n = [0]
    inserted = set()

    def repl(m):
        num = m.group(2)
        pg = pages.get(num)
        if not pg:
            return m.group(0)
        n[0] += 1
        inserted.add(str(pg))
        return '%s<span class="n">%s</span>%s<span class="pg">%d</span>' % (
            m.group(1), num, m.group(3), pg)

    html = re.sub(r'(<a href="#sec-\d+">)<span class="n">(\d+)</span>'
                  r'(<span>[^<]*</span>)', repl, html)
    return html, n[0], inserted


def paginate(html_path, pdf_path, footer_left="", also_write=(), draft_note="", draft_marker=""):
    """Add contents page numbers and a PDF outline. Re-renders, then VERIFIES nothing moved.

    THE PAGINATED HTML IS NEVER WRITTEN BACK OVER `html_path`. This function used to read the
    published HTML, insert the page numbers and the print CSS, and write the file back, after
    the claims gate had judged it, and after the versioned edition had been copied. The file a
    reader received was therefore not the file that was verified, and no exit code anywhere said
    so. Nothing that runs after the gate may edit an artifact the gate passed; a second pass that
    needs a changed document works on a copy and throws it away. The copy sits beside the original
    only so that relative links and assets resolve identically, and it is deleted before returning
    whatever happens.

    `also_write` are extra paths to receive the finished PDF, for a versioned edition alongside a
    working copy. An .html destination is REFUSED: publishing the working copy is exactly the
    mutation this function no longer performs.

    `draft_note` and `draft_marker` are passed through to the re-render, so the second pass keeps
    the stamp the first pass carried. Losing them here would produce an unstamped final PDF from a
    stamped draft.
    """
    if not os.path.exists(pdf_path):
        raise SystemExit("render the PDF before paginating: %s is missing" % pdf_path)
    stray = [d for d in also_write if d.endswith(".html")]
    if stray:
        raise SystemExit(
            "paginate() will not write HTML: %s. The paginated document is a working copy that "
            "the claims gate never saw, so copying it over a published edition would replace a "
            "verified file with an unverified one." % ", ".join(stray))
    pages = section_pages(pdf_path)
    if not pages:
        raise SystemExit("found no section headings in the PDF; refusing to write a contents page "
                         "with guessed numbers")

    html = io.open(html_path, encoding="utf-8").read()
    if 'class="pg"' in html:
        raise SystemExit("contents already paginated; rebuild the HTML first")
    html, n, inserted = _patch_contents(html, pages)
    if n < len(pages) - 1:
        raise SystemExit("only matched %d of %d sections in the contents; not shipping a partial "
                         "contents page" % (n, len(pages)))

    # display:block makes each row a full-width line so the page number can float right. That also
    # collapses the gap the screen layout got from flex, so the number column is given a width back.
    css = ("\n  nav.toc .pg{float:right;color:var(--muted);font-variant-numeric:tabular-nums}"
           "\n  nav.toc li a{display:block}"
           "\n  nav.toc .n{display:inline-block;min-width:2.1em;text-align:left}\n")
    html = html.replace("@media print{", "@media print{" + css, 1)

    # Beside the original, not in a temp dir: a report references its own directory for anything
    # it does not inline, and rendering from elsewhere would silently drop it. The leading dot and
    # the suffix make it unmistakably not a publishable artifact, and the finally clause removes it
    # even when the render raises.
    work_path = os.path.join(os.path.dirname(os.path.abspath(html_path)),
                             ".paginating-" + os.path.basename(html_path))
    try:
        io.open(work_path, "w", encoding="utf-8", newline="\n").write(html)
        render(work_path, pdf_path, footer_left=footer_left, draft_note=draft_note,
               draft_marker=draft_marker)
    finally:
        if os.path.exists(work_path):
            try:
                os.unlink(work_path)
            except OSError:
                pass

    after = section_pages(pdf_path)
    drift = {k: (pages[k], after[k]) for k in pages if k in after and pages[k] != after[k]}

    fitz = _require("fitz", "attach a PDF outline")
    doc = fitz.open(pdf_path)
    toc = []
    for num in sorted(after, key=int):
        page = doc[after[num] - 1]
        title = None
        for line in page.get_text().split("\n"):
            m = re.match(r"^(%s)\.\s+(\S.*)$" % re.escape(num), line.strip())
            if m:
                title = "%s. %s" % (num, m.group(2))
                break
        toc.append([1, title or ("Section " + num), after[num]])
    doc.set_toc(toc)
    if draft_marker:
        # Metadata as well as the footer: this is where an Office-aware or PDF-aware tool looks,
        # and the footer is where a text extraction finds it. Neither alone covers both readers.
        meta = dict(doc.metadata or {})
        meta["keywords"] = ("%s %s" % (draft_marker, meta.get("keywords") or "")).strip()
        meta["subject"] = draft_note or draft_marker
        doc.set_metadata(meta)
    doc.saveIncr()
    doc.close()

    for dst in also_write:
        if os.path.exists(pdf_path):
            io.open(dst, "wb").write(io.open(pdf_path, "rb").read())

    return {"sections": n, "outline_entries": len(toc), "drift": drift,
            "verified": not drift,
            # Every numeral this pass put into the PDF that its source document does not contain.
            # The caller compares the PDF's numerals against the judged HTML's, and these are the
            # accounted difference: named, not a tolerated range.
            "inserted": sorted(inserted | {str(p) for p in after.values()}, key=int),
            # The property the caller has to be able to assert on: pagination touched a working
            # copy and left the judged document alone.
            "html_untouched": True, "worked_on": work_path}
